<h1>Project: Family Income and Expenditure</h1>

<h2>Analyst: Serna Tricia and Palas Jamaica</h2>

---

In [61]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error, r2_score

In [62]:
df = pd.read_csv("Family Income and Expenditure.csv")

In [63]:
df.head()

Total Household Income Region  Total Food Expenditure  \
0                  480332    CAR                  117848   
1                  198235    CAR                   67766   
2                   82785    CAR                   61609   
3                  107589    CAR                   78189   
4                  189322    CAR                   94625   

  Main Source of Income  Agricultural Household indicator  \
0         Wage/Salaries                                 0   
1         Wage/Salaries                                 0   
2         Wage/Salaries                                 1   
3         Wage/Salaries                                 0   
4         Wage/Salaries                                 0   

   Bread and Cereals Expenditure  Total Rice Expenditure  Meat Expenditure  \
0                          42140                   38300             24676   
1                          17329                   13008             17434   
2                          34182                   32001              7783   
3                          34030                   28659             10914   
4                          34820                   30167             18391   

   Total Fish and  marine products Expenditure  Fruit Expenditure  ...  \
0                                        16806               3325  ...   
1                                        11073               2035  ...   
2                                         2590               1730  ...   
3                                        10812                690  ...   
4                                        11309               1395  ...   

   Number of Refrigerator/Freezer  Number of Washing Machine  \
0                               1                          1   
1                               0                          1   
2                               0                          0   
3                               0                          0   
4                               1                          0   

   Number of Airconditioner  Number of Car, Jeep, Van  \
0                         0                         0   
1                         0                         0   
2                         0                         0   
3                         0                         0   
4                         0                         0   

   Number of Landline/wireless telephones  Number of Cellular phone  \
0                                       0                         2   
1                                       0                         3   
2                                       0                         0   
3                                       0                         1   
4                                       0                         3   

   Number of Personal Computer  Number of Stove with Oven/Gas Range  \
0                            1                                    0   
1                            1                                    0   
2                            0                                    0   
3                            0                                    0   
4                            0                                    0   

   Number of Motorized Banca  Number of Motorcycle/Tricycle  
0                          0                              1  
1                          0                              2  
2                          0                              0  
3                          0                              0  
4                          0                              1  

[5 rows x 60 columns]

In [64]:
calabarzon = df[df["Region"] == "IVA - CALABARZON"].copy()
calabarzon.shape

(4162, 60)

<h2>INSIGHT: Region 4A contains 4,162 households, a large enough sample to accurately reflect the socioeconomic conditions of CALABARZON families.</h2>

In [65]:
calabarzon.columns.tolist()

['Total Household Income',
 'Region',
 'Total Food Expenditure',
 'Main Source of Income',
 'Agricultural Household indicator',
 'Bread and Cereals Expenditure',
 'Total Rice Expenditure',
 'Meat Expenditure',
 'Total Fish and  marine products Expenditure',
 'Fruit Expenditure',
 'Vegetables Expenditure',
 'Restaurant and hotels Expenditure',
 'Alcoholic Beverages Expenditure',
 'Tobacco Expenditure',
 'Clothing, Footwear and Other Wear Expenditure',
 'Housing and water Expenditure',
 'Imputed House Rental Value',
 'Medical Care Expenditure',
 'Transportation Expenditure',
 'Communication Expenditure',
 'Education Expenditure',
 'Miscellaneous Goods and Services Expenditure',
 'Special Occasions Expenditure',
 'Crop Farming and Gardening expenses',
 'Total Income from Entrepreneurial Acitivites',
 'Household Head Sex',
 'Household Head Age',
 'Household Head Marital Status',
 'Household Head Highest Grade Completed',
 'Household Head Job or Business Indicator',
 'Household Head Occupat

In [66]:
calabarzon = calabarzon.dropna(axis=1, how="all")
calabarzon = calabarzon.fillna(0)
calabarzon.head()


Total Household Income            Region  Total Food Expenditure  \
2520                  118410  IVA - CALABARZON                   71019   
2521                  151380  IVA - CALABARZON                   80889   
2522                  282373  IVA - CALABARZON                  112023   
2523                  146190  IVA - CALABARZON                   77491   
2524                   95530  IVA - CALABARZON                   67688   

        Main Source of Income  Agricultural Household indicator  \
2520            Wage/Salaries                                 0   
2521            Wage/Salaries                                 0   
2522            Wage/Salaries                                 0   
2523            Wage/Salaries                                 0   
2524  Other sources of Income                                 0   

      Bread and Cereals Expenditure  Total Rice Expenditure  Meat Expenditure  \
2520                          27477                   24160             10688   
2521                          26307                   22600             14007   
2522                          32817                   29250             18110   
2523                          20390                   14313             15072   
2524                          28642                   26000             13429   

      Total Fish and  marine products Expenditure  Fruit Expenditure  ...  \
2520                                        10280               1090  ...   
2521                                         6578               1790  ...   
2522                                        13496                850  ...   
2523                                         9682               1310  ...   
2524                                         5024                850  ...   

      Number of Refrigerator/Freezer  Number of Washing Machine  \
2520                               0                          0   
2521                               0                          1   
2522                               0                          1   
2523                               0                          0   
2524                               0                          0   

      Number of Airconditioner  Number of Car, Jeep, Van  \
2520                         0                         0   
2521                         0                         0   
2522                         0                         0   
2523                         0                         0   
2524                         0                         0   

      Number of Landline/wireless telephones  Number of Cellular phone  \
2520                                       0                         2   
2521                                       0                         2   
2522                                       0                         2   
2523                                       0                         1   
2524                                       0                         1   

      Number of Personal Computer  Number of Stove with Oven/Gas Range  \
2520                            0                                    0   
2521                            0                                    0   
2522                            1                                    0   
2523                            0                                    0   
2524                            0                                    0   

      Number of Motorized Banca  Number of Motorcycle/Tricycle  
2520                          0                              0  
2521                          0                              0  
2522                          0                              0  
2523                          0                              1  
2524                          0                              0  

[5 rows x 60 columns]

In [67]:
calabarzon.describe()

Total Household Income  Total Food Expenditure  \
count            4.162000e+03             4162.000000   
mean             3.033605e+05           105333.949543   
std              2.819202e+05            58274.664810   
min              1.844100e+04             6649.000000   
25%              1.419100e+05            64606.000000   
50%              2.277570e+05            94760.000000   
75%              3.701928e+05           132076.500000   
max              4.349214e+06           656954.000000   

       Agricultural Household indicator  Bread and Cereals Expenditure  \
count                       4162.000000                    4162.000000   
mean                           0.069678                   24571.531716   
std                            0.254634                   11812.560636   
min                            0.000000                       0.000000   
25%                            0.000000                   16312.000000   
50%                            0.000000                   22951.000000   
75%                            0.000000                   30981.750000   
max                            1.000000                  124696.000000   

       Total Rice Expenditure  Meat Expenditure  \
count             4162.000000       4162.000000   
mean             17260.889957      15090.317876   
std               9277.713934      11953.449362   
min                  0.000000          0.000000   
25%              11050.000000       6219.250000   
50%              15300.000000      12495.000000   
75%              22437.000000      20725.500000   
max             116100.000000     107265.000000   

       Total Fish and  marine products Expenditure  Fruit Expenditure  \
count                                  4162.000000        4162.000000   
mean                                  10737.155935        2938.367612   
std                                    6951.507106        3128.677959   
min                                       0.000000           0.000000   
25%                                    6040.000000        1110.000000   
50%                                    9367.500000        2065.000000   
75%                                   13776.000000        3591.500000   
max                                   63061.000000       40340.000000   

       Vegetables Expenditure  Restaurant and hotels Expenditure  ...  \
count             4162.000000                        4162.000000  ...   
mean              4968.399568                       27326.596828  ...   
std               3529.676111                       28140.149902  ...   
min                  0.000000                           0.000000  ...   
25%               2685.250000                        9040.000000  ...   
50%               4232.500000                       20325.000000  ...   
75%               6358.750000                       36650.000000  ...   
max              49810.000000                      481600.000000  ...   

       Number of Refrigerator/Freezer  Number of Washing Machine  \
count                     4162.000000                4162.000000   
mean                         0.518741                   0.512975   
std                          0.551818                   0.520154   
min                          0.000000                   0.000000   
25%                          0.000000                   0.000000   
50%                          0.000000                   1.000000   
75%                          1.000000                   1.000000   
max                          5.000000                   3.000000   

       Number of Airconditioner  Number of Car, Jeep, Van  \
count               4162.000000               4162.000000   
mean                   0.177559                  0.111004   
std                    0.482768                  0.409194   
min                    0.000000                  0.000000   
25%                    0.000000                  0.000000   
50%                    0.000000                  0.000000   
75%       

In [70]:
calabarzon[["Total Household Income", "Total Food Expenditure"]].mean()

Total Household Income    303360.536040
Total Food Expenditure    105333.949543
dtype: float64

<h2>INSIGHT: Average income and food spending reveal that food is a major cost, consuming a large portion of household budgets.</h2>

<h2> Insight: On average, families in IVA - CALABARZON spend $34.7\%$ of their income ($\text{P}105,334$ out of $\text{P}303,361$) on food, highlighting a significant financial burden and vulnerability to price changes in basic necessities.</h2>

In [71]:
calabarzon[["Total Household Income", "Total Food Expenditure"]].max()

Total Household Income    4349214
Total Food Expenditure     656954
dtype: int64

<h2>INSIGHT: Some households earn up to ₱4.3M annually, and spend over ₱650k on food, reflecting the presence of affluent families in Region 4A.</h2>

In [72]:
calabarzon[["Total Household Income", "Total Food Expenditure"]].min()

Total Household Income    18441
Total Food Expenditure     6649
dtype: int64

<h2>Insight: Some families earn as low as ₱18,441 yearly, showing severe poverty and extremely limited spending power in the lower-income sectors.</h2>

In [73]:
calabarzon["Agricultural Household indicator"].value_counts()

Agricultural Household indicator
0    3872
1     290
Name: count, dtype: int64

<h2>Insight: Only about 7% of households are agriculture-based—Region 4A is heavily urbanized and industrial, not agricultural.</h2>

In [75]:
calabarzon["Number of Car, Jeep, Van"].mean()

np.float64(0.11100432484382508)

<h2>Insight: Vehicle ownership is relatively low on average, but still present, indicating a mix of middle-class and working-class families.</h2>

In [76]:
calabarzon["Toilet Facilities"].value_counts()

Toilet Facilities
Water-sealed, sewer septic tank, used exclusively by household    3650
Water-sealed, sewer septic tank, shared with other household       296
0                                                                  112
Closed pit                                                          40
Water-sealed, other depository, used exclusively by household       36
Open pit                                                            17
Water-sealed, other depository, shared with other household         11
Name: count, dtype: int64

<h2>Insight: Most households have adequate toilet facilities, showing good sanitation infrastructure, but a minority still lack proper sanitation.</h2>

In [77]:
calabarzon.isnull().sum()

Total Household Income                           0
Region                                           0
Total Food Expenditure                           0
Main Source of Income                            0
Agricultural Household indicator                 0
Bread and Cereals Expenditure                    0
Total Rice Expenditure                           0
Meat Expenditure                                 0
Total Fish and  marine products Expenditure      0
Fruit Expenditure                                0
Vegetables Expenditure                           0
Restaurant and hotels Expenditure                0
Alcoholic Beverages Expenditure                  0
Tobacco Expenditure                              0
Clothing, Footwear and Other Wear Expenditure    0
Housing and water Expenditure                    0
Imputed House Rental Value                       0
Medical Care Expenditure                         0
Transportation Expenditure                       0
Communication Expenditure      

In [78]:
calabarzon["Total Household Income"].corr(calabarzon["Total Food Expenditure"])

np.float64(0.7438792954078179)

<h2>Insight: A strong positive correlation indicates that as income increases, food expenditure also rises, consistent with economic behavior.</h2>

In [81]:
calabarzon["Food_Percent"] = calabarzon["Total Food Expenditure"] / calabarzon["Total Household Income"]
calabarzon["Food_Percent"].describe()

count    4162.000000
mean        0.423222
std         0.150309
min         0.042151
25%         0.315073
50%         0.419222
75%         0.525255
max         1.065024
Name: Food_Percent, dtype: float64

<h2>Insight: Lower-income households spend 40–70% of their income on food, while higher-income households spend far less — a sign of economic strain for poorer families.</h2>

In [82]:
calabarzon["Total Household Income"].skew()

np.float64(4.516394372012084)

<h2>Insight: Income is highly right-skewed, confirming that a few wealthy families strongly pull the income distribution upward.</h2>

In [84]:
calabarzon.groupby("Agricultural Household indicator")["Total Household Income"].mean()

Agricultural Household indicator
0    315427.785124
1    142241.955172
Name: Total Household Income, dtype: float64

<h2>Inisght: Agricultural households earn significantly less than non-agricultural households, reflecting urban–rural economic disparities within Region 4A.</h2>

In [92]:
calabarzon.groupby("Household Head Highest Grade Completed")["Total Household Income"].mean()

Household Head Highest Grade Completed
Agriculture, Forestry, and Fishery Programs                                                                                                                                                                            6.886901e+05
Architecture and Building Programs                                                                                                                                                                                     8.626300e+05
Arts Programs                                                                                                                                                                                                          6.701210e+05
Basic Programs                                                                                                                                                                                                         4.543265e+05
Business and Administration Programs             

<h2>Insight: Households where the head has higher educational attainment consistently show much higher total income. This confirms that education is one of the strongest socioeconomic predictors of financial well-being in Region 4A.
Those with only elementary schooling earn the lowest, while those with college or postgraduate education earn significantly more.</h2>

In [93]:
calabarzon["Total Household Income"].corr(calabarzon["Total Number of Family members"])

np.float64(0.19871409572372897)

<h2>Insight: The correlation between income and the total number of family members in CALABARZON is very weak.
This means family size does not strongly determine a household’s earning capacity.
Large families are not necessarily poorer or richer — income levels vary widely regardless of how many household members they have.</h2>

---

In [94]:
features = [
    "Total Food Expenditure",
    "Transportation Expenditure",
    "Education Expenditure",
    "Medical Care Expenditure",
    "Total Number of Family members",
    "Household Head Age"
]

X = calabarzon[features]
y = calabarzon["Total Household Income"]

In [95]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

<h>Insight: The training and testing split allows us to evaluate how well the model predicts income for unseen Region 4A households.</h2>

In [97]:
from sklearn.linear_model import LinearRegression

lin_model = LinearRegression()
lin_model.fit(X_train, y_train)

LinearRegression()

<h2>Insight: Linear regression provides a baseline model, showing how income changes with each predictor in a simple linear relationship.</h2>

In [98]:
lin_score = lin_model.score(X_test, y_test)
lin_score

0.7603989391654472

<h2>The linear regression R² score indicates how much variance in household income the model can explain using the selected predictors.</h2>

In [100]:
coeffs = dict(zip(features, lin_model.coef_))
coeffs

{'Total Food Expenditure': np.float64(2.5153580135610873),
 'Transportation Expenditure': np.float64(4.367873806618682),
 'Education Expenditure': np.float64(1.1040914865229539),
 'Medical Care Expenditure': np.float64(1.0721309632798135),
 'Total Number of Family members': np.float64(-20790.948409244374),
 'Household Head Age': np.float64(894.6758120819322)}

<h2>The coefficients show which expenditures or characteristics positively or negatively impact income.
For example: higher education or transportation spending tends to correlate with higher income.</h2>

In [101]:
from sklearn.tree import DecisionTreeRegressor

tree_model = DecisionTreeRegressor(random_state=42)
tree_model.fit(X_train, y_train)

DecisionTreeRegressor(random_state=42)

<h2>Decision trees capture non-linear relationships, making them useful for income data with large variability and outliers.</h2>

In [102]:
tree_score = tree_model.score(X_test, y_test)
tree_score

0.2322895453751047

<h2>The decision tree usually performs better than linear regression because Region 4A income patterns are non-linear and complex.</h2>

In [104]:
lin_predictions = lin_model.predict(X_test)
lin_predictions[:10]

array([ 54177.78614344, 281404.48515927, 225310.40098437, 378319.00144871,
       117242.13289606, 147048.59044643, 243593.62200078, 421419.10058784,
       362054.00972859, 308393.13263533])

<h2>Linear regression predictions show smooth and moderate estimates, often underestimating very high-income households because the relationship is not perfectly linear.</h2>

In [ ]:
tree_predictions = tree_model.predict(X_test)
tree_predictions[:10]